apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app-blue
  labels:
    app: django-messaging-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: django-messaging-app
        version: blue
    spec:
      containers:
        - name: django-app
          image: <your-dockerhub-username>/django-messaging-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: messaging_app.settings
            - name: DATABASE_URL
              value: postgres://user:password@db-host/db-name
---
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-app-blue-service
spec:
  selector:
    app: django-messaging-app
    version: blue
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
